name: GitHub-Profile-Summary-Cards

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate

    steps:
      - uses: actions/checkout@v2

      - name: Set git identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create and switch to new branch
        run: |
          git fetch origin
          git checkout -b generated-summary-branch || git checkout generated-summary-branch

      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}

      - name: Push to new branch
        run: |
          git add .
          git commit -m "Update profile summary cards [skip ci]" || echo "Nothing to commit"
          git push origin generated-summary-branch

